spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootex
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  swagger-ui:
    path: /
  default-consumes-media-type: application/json
  default-produces-media-type: application/json